import { TTSModel } from "@/types";

export const MODELS: TTSModel[] = [
  {
    id: "mms-tts-fas",
    name: "Meta MMS-TTS (Persian)",
    description: "Persian-specific TTS model by Meta AI based on VITS architecture. Lightweight and fast, optimized for Persian/Farsi speech synthesis.",
    huggingfaceId: "facebook/mms-tts-fas",
    vramRequired: 1,
    languages: ["fa"],
    capabilities: ["persian-optimized", "lightweight", "fast"],
    localDir: "models/mms-tts-fas",
  },
  {
    id: "omnivoice",
    name: "OmniVoice",
    description: "Massively multilingual zero-shot TTS with voice design attributes. Supports 600+ languages.",
    huggingfaceId: "k2-fsa/OmniVoice",
    vramRequired: 4,
    languages: ["fa", "en", "ar", "zh", "ja", "ko", "es", "fr", "de", "ru", "pt", "it", "hi", "tr"],
    capabilities: ["voice-cloning", "voice-design", "600-languages", "zero-shot", "emotion-tags"],
    localDir: "models/omnivoice",
  },
  {
    id: "piper-fa-amir",
    name: "Piper TTS Persian (Amir)",
    description: "Lightweight Persian TTS voice based on Piper (ONNX runtime). Amir is a male voice trained on Persian data. Extremely fast on CPU.",
    huggingfaceId: "rhasspy/piper-voices",
    vramRequired: 0,
    languages: ["fa"],
    capabilities: ["persian-optimized", "lightweight", "cpu-friendly", "male-voice"],
    localDir: "models/piper-fa",
  },
  {
    id: "piper-fa-gyro",
    name: "Piper TTS Persian (Gyro)",
    description: "Lightweight Persian TTS voice based on Piper (ONNX runtime). Gyro is another Persian voice, fast on CPU.",
    huggingfaceId: "rhasspy/piper-voices",
    vramRequired: 0,
    languages: ["fa"],
    capabilities: ["persian-optimized", "lightweight", "cpu-friendly"],
    localDir: "models/piper-fa",
  },
  {
    id: "ims-toucan",
    name: "IMS ToucanTTS (Persian)",
    description: "Massively multilingual FastSpeech2-based TTS from University of Stuttgart. Supports 7000+ languages including Persian. Higher quality than Piper, runs on CPU. Uses FastSpeech2 architecture with HiFi-GAN vocoder.",
    huggingfaceId: "Flux9665/ToucanTTS",
    vramRequired: 0,
    languages: ["fa", "en", "ar", "tr", "az", "ku", "ur", "prs", "tg"],
    capabilities: ["persian-optimized", "multilingual", "voice-cloning", "prosody-control", "7000-languages"],
    localDir: "models/ims-toucan",
  },
  {
    id: "mana-piper",
    name: "Mana Persian Piper",
    description: "A Piper checkpoint fine-tuned on the Mana-TTS dataset. Lightweight, low-latency, high-quality Persian speech. MIT licensed, runs on CPU (no GPU required).",
    huggingfaceId: "MahtaFetrat/Mana-Persian-Piper",
    vramRequired: 0,
    languages: ["fa"],
    capabilities: ["persian-optimized", "lightweight", "cpu-friendly", "mit-license"],
    localDir: "models/mana-piper",
  },
  {
    id: "pertts-amir",
    name: "Pertts Persian (Amir)",
    description: "Fast Persian TTS voice based on Piper/ONNX runtime. Amir variant — natural sounding male voice. Extremely fast on CPU.",
    huggingfaceId: "SadeghK/persian-text-to-speech",
    vramRequired: 0,
    languages: ["fa"],
    capabilities: ["persian-optimized", "lightweight", "cpu-friendly", "male-voice"],
    localDir: "models/pertts",
  },
  {
    id: "pertts-ganji",
    name: "Pertts Persian (Ganji)",
    description: "Fast Persian TTS voice based on Piper/ONNX runtime. Ganji variant — another natural Persian male voice. CPU-friendly.",
    huggingfaceId: "SadeghK/persian-text-to-speech",
    vramRequired: 0,
    languages: ["fa"],
    capabilities: ["persian-optimized", "lightweight", "cpu-friendly"],
    localDir: "models/pertts",
  },
  {
    id: "pertts-ganji-adabi",
    name: "Pertts Persian (Ganji Adabi)",
    description: "Fast Persian TTS voice based on Piper/ONNX runtime. Ganji Adabi variant — literary Persian voice. CPU-friendly.",
    huggingfaceId: "SadeghK/persian-text-to-speech",
    vramRequired: 0,
    languages: ["fa"],
    capabilities: ["persian-optimized", "lightweight", "cpu-friendly", "literary-voice"],
    localDir: "models/pertts",
  },
  {
    id: "kamtera-male-vits",
    name: "Kamtera Male VITS",
    description: "Coqui-format VITS Persian male voice. ~950 MB model. Requires Coqui TTS (Python <3.12). High-quality neural TTS.",
    huggingfaceId: "Kamtera/persian-tts-male1-vits",
    vramRequired: 2,
    languages: ["fa"],
    capabilities: ["persian-optimized", "vits", "male-voice", "high-quality"],
    localDir: "models/kamtera-male-vits",
  },
  {
    id: "kamtera-female-vits",
    name: "Kamtera Female VITS",
    description: "Coqui-format VITS Persian female voice. ~950 MB model. Requires Coqui TTS (Python <3.12). High-quality neural TTS.",
    huggingfaceId: "Kamtera/persian-tts-female-vits",
    vramRequired: 2,
    languages: ["fa"],
    capabilities: ["persian-optimized", "vits", "female-voice", "high-quality"],
    localDir: "models/kamtera-female-vits",
  },
];

export function getModelById(id: string): TTSModel | undefined {
  return MODELS.find((m) => m.id === id);
}
